name: Verify changes

on: pull_request

jobs:
  verify:
    name: Verify changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - uses: microsoft/playwright-github-action@v1

      - name: Test
        run: npm run test